import type { ApprovalTimelineDataPoint, TimelineStage } from "./types"

// Sample historical approval timeline data
export const approvalHistoricalData: ApprovalTimelineDataPoint[] = [
  {
    id: "ap1",
    city: "Los Angeles",
    county: "Los Angeles",
    projectType: "single-family",
    projectSize: "medium",
    approvalType: "building-permit",
    durationDays: 45,
    startDate: "2023-01-15",
    endDate: "2023-03-01",
    outcome: "approved",
    complexity: 3,
  },
  {
    id: "ap2",
    city: "Los Angeles",
    county: "Los Angeles",
    projectType: "multi-family",
    projectSize: "large",
    approvalType: "building-permit",
    durationDays: 120,
    startDate: "2022-09-10",
    endDate: "2023-01-08",
    outcome: "approved",
    complexity: 7,
  },
  {
    id: "ap3",
    city: "Los Angeles",
    county: "Los Angeles",
    projectType: "single-family",
    projectSize: "small",
    approvalType: "zoning-variance",
    durationDays: 75,
    startDate: "2022-11-05",
    endDate: "2023-01-19",
    outcome: "approved",
    complexity: 5,
  },
  {
    id: "ap4",
    city: "San Francisco",
    county: "San Francisco",
    projectType: "mixed-use",
    projectSize: "large",
    approvalType: "environmental-review",
    durationDays: 210,
    startDate: "2022-06-12",
    endDate: "2023-01-08",
    outcome: "approved",
    complexity: 9,
  },
  {
    id: "ap5",
    city: "San Francisco",
    county: "San Francisco",
    projectType: "multi-family",
    projectSize: "medium",
    approvalType: "design-review",
    durationDays: 90,
    startDate: "2022-10-15",
    endDate: "2023-01-13",
    outcome: "approved",
    complexity: 6,
  },
  {
    id: "ap6",
    city: "San Diego",
    county: "San Diego",
    projectType: "single-family",
    projectSize: "small",
    approvalType: "building-permit",
    durationDays: 30,
    startDate: "2023-02-01",
    endDate: "2023-03-03",
    outcome: "approved",
    complexity: 2,
  },
  {
    id: "ap7",
    city: "San Diego",
    county: "San Diego",
    projectType: "commercial",
    projectSize: "large",
    approvalType: "conditional-use",
    durationDays: 150,
    startDate: "2022-08-15",
    endDate: "2023-01-12",
    outcome: "approved",
    complexity: 8,
  },
  {
    id: "ap8",
    city: "Sacramento",
    county: "Sacramento",
    projectType: "multi-family",
    projectSize: "medium",
    approvalType: "building-permit",
    durationDays: 60,
    startDate: "2022-12-01",
    endDate: "2023-01-30",
    outcome: "approved",
    complexity: 4,
  },
  {
    id: "ap9",
    city: "Oakland",
    county: "Alameda",
    projectType: "mixed-use",
    projectSize: "large",
    approvalType: "design-review",
    durationDays: 120,
    startDate: "2022-09-10",
    endDate: "2023-01-08",
    outcome: "approved",
    complexity: 7,
  },
  {
    id: "ap10",
    city: "San Jose",
    county: "Santa Clara",
    projectType: "commercial",
    projectSize: "medium",
    approvalType: "environmental-review",
    durationDays: 180,
    startDate: "2022-07-15",
    endDate: "2023-01-11",
    outcome: "approved",
    complexity: 8,
  },
  {
    id: "ap11",
    city: "Fresno",
    county: "Fresno",
    projectType: "single-family",
    projectSize: "small",
    approvalType: "building-permit",
    durationDays: 35,
    startDate: "2023-01-25",
    endDate: "2023-03-01",
    outcome: "approved",
    complexity: 2,
  },
  {
    id: "ap12",
    city: "Long Beach",
    county: "Los Angeles",
    projectType: "multi-family",
    projectSize: "medium",
    approvalType: "zoning-variance",
    durationDays: 90,
    startDate: "2022-10-20",
    endDate: "2023-01-18",
    outcome: "approved",
    complexity: 6,
  },
  {
    id: "ap13",
    city: "Berkeley",
    county: "Alameda",
    projectType: "mixed-use",
    projectSize: "medium",
    approvalType: "design-review",
    durationDays: 105,
    startDate: "2022-09-25",
    endDate: "2023-01-08",
    outcome: "approved",
    complexity: 7,
  },
  {
    id: "ap14",
    city: "Irvine",
    county: "Orange",
    projectType: "commercial",
    projectSize: "large",
    approvalType: "building-permit",
    durationDays: 75,
    startDate: "2022-11-15",
    endDate: "2023-01-29",
    outcome: "approved",
    complexity: 5,
  },
  {
    id: "ap15",
    city: "Santa Monica",
    county: "Los Angeles",
    projectType: "multi-family",
    projectSize: "large",
    approvalType: "environmental-review",
    durationDays: 240,
    startDate: "2022-05-10",
    endDate: "2023-01-05",
    outcome: "approved",
    complexity: 9,
  },
  {
    id: "ap16",
    city: "Pasadena",
    county: "Los Angeles",
    projectType: "single-family",
    projectSize: "medium",
    approvalType: "design-review",
    durationDays: 60,
    startDate: "2022-12-10",
    endDate: "2023-02-08",
    outcome: "approved",
    complexity: 4,
  },
  {
    id: "ap17",
    city: "Santa Barbara",
    county: "Santa Barbara",
    projectType: "single-family",
    projectSize: "large",
    approvalType: "design-review",
    durationDays: 90,
    startDate: "2022-10-15",
    endDate: "2023-01-13",
    outcome: "approved",
    complexity: 6,
  },
  {
    id: "ap18",
    city: "Palo Alto",
    county: "Santa Clara",
    projectType: "mixed-use",
    projectSize: "medium",
    approvalType: "conditional-use",
    durationDays: 120,
    startDate: "2022-09-01",
    endDate: "2022-12-30",
    outcome: "approved",
    complexity: 7,
  },
  {
    id: "ap19",
    city: "Los Angeles",
    county: "Los Angeles",
    projectType: "adu",
    projectSize: "small",
    approvalType: "building-permit",
    durationDays: 40,
    startDate: "2023-01-10",
    endDate: "2023-02-19",
    outcome: "approved",
    complexity: 3,
  },
  {
    id: "ap20",
    city: "San Francisco",
    county: "San Francisco",
    projectType: "adu",
    projectSize: "small",
    approvalType: "building-permit",
    durationDays: 60,
    startDate: "2022-12-01",
    endDate: "2023-01-30",
    outcome: "approved",
    complexity: 4,
  },
  {
    id: "ap21",
    city: "Los Angeles",
    county: "Los Angeles",
    projectType: "multi-family",
    projectSize: "large",
    approvalType: "conditional-use",
    durationDays: 160,
    startDate: "2022-08-01",
    endDate: "2023-01-08",
    outcome: "denied",
    complexity: 8,
  },
  {
    id: "ap22",
    city: "San Diego",
    county: "San Diego",
    projectType: "mixed-use",
    projectSize: "large",
    approvalType: "zoning-variance",
    durationDays: 110,
    startDate: "2022-09-15",
    endDate: "2023-01-03",
    outcome: "withdrawn",
    complexity: 7,
  },
  {
    id: "ap23",
    city: "Oakland",
    county: "Alameda",
    projectType: "multi-family",
    projectSize: "medium",
    approvalType: "environmental-review",
    durationDays: 170,
    startDate: "2022-07-25",
    endDate: "2023-01-11",
    outcome: "denied",
    complexity: 8,
  },
  {
    id: "ap24",
    city: "Huntington Beach",
    county: "Orange",
    projectType: "single-family",
    projectSize: "medium",
    approvalType: "building-permit",
    durationDays: 50,
    startDate: "2022-12-20",
    endDate: "2023-02-08",
    outcome: "approved",
    complexity: 3,
  },
  {
    id: "ap25",
    city: "Newport Beach",
    county: "Orange",
    projectType: "single-family",
    projectSize: "large",
    approvalType: "design-review",
    durationDays: 75,
    startDate: "2022-11-10",
    endDate: "2023-01-24",
    outcome: "approved",
    complexity: 5,
  },
  {
    id: "ap26",
    city: "San Francisco",
    county: "San Francisco",
    projectType: "multi-family",
    projectSize: "large",
    approvalType: "conditional-use",
    durationDays: 180,
    startDate: "2022-07-15",
    endDate: "2023-01-11",
    outcome: "approved",
    complexity: 8,
  },
  {
    id: "ap27",
    city: "Los Angeles",
    county: "Los Angeles",
    projectType: "commercial",
    projectSize: "large",
    approvalType: "environmental-review",
    durationDays: 210,
    startDate: "2022-06-15",
    endDate: "2023-01-11",
    outcome: "approved",
    complexity: 9,
  },
  {
    id: "ap28",
    city: "San Jose",
    county: "Santa Clara",
    projectType: "single-family",
    projectSize: "small",
    approvalType: "building-permit",
    durationDays: 40,
    startDate: "2023-01-05",
    endDate: "2023-02-14",
    outcome: "approved",
    complexity: 2,
  },
  {
    id: "ap29",
    city: "San Diego",
    county: "San Diego",
    projectType: "adu",
    projectSize: "small",
    approvalType: "building-permit",
    durationDays: 35,
    startDate: "2023-01-15",
    endDate: "2023-02-19",
    outcome: "approved",
    complexity: 2,
  },
  {
    id: "ap30",
    city: "Berkeley",
    county: "Alameda",
    projectType: "multi-family",
    projectSize: "medium",
    approvalType: "design-review",
    durationDays: 95,
    startDate: "2022-10-10",
    endDate: "2023-01-13",
    outcome: "approved",
    complexity: 6,
  },
]

// Timeline stages for different approval types
export const timelineStages: Record<string, TimelineStage[]> = {
  "building-permit": [
    {
      name: "Application Submission",
      avgDuration: 1,
      description: "Initial application submission and fee payment",
      riskLevel: "low",
      order: 1,
    },
    {
      name: "Completeness Review",
      avgDuration: 10,
      description: "Staff review to ensure all required documents are provided",
      riskLevel: "medium",
      order: 2,
    },
    {
      name: "Plan Check",
      avgDuration: 20,
      description: "Detailed review of plans for code compliance",
      riskLevel: "high",
      order: 3,
    },
    {
      name: "Corrections",
      avgDuration: 15,
      description: "Revisions based on plan check comments",
      riskLevel: "medium",
      order: 4,
    },
    {
      name: "Final Approval",
      avgDuration: 5,
      description: "Final review and permit issuance",
      riskLevel: "low",
      order: 5,
    },
  ],
  "conditional-use": [
    {
      name: "Pre-Application Meeting",
      avgDuration: 7,
      description: "Initial consultation with planning staff",
      riskLevel: "low",
      order: 1,
    },
    {
      name: "Application Submission",
      avgDuration: 1,
      description: "Formal application submission with required materials",
      riskLevel: "low",
      order: 2,
    },
    {
      name: "Staff Review",
      avgDuration: 30,
      description: "Planning department review of application",
      riskLevel: "medium",
      order: 3,
    },
    {
      name: "Environmental Review",
      avgDuration: 45,
      description: "CEQA compliance review",
      riskLevel: "high",
      order: 4,
    },
    {
      name: "Public Notice",
      avgDuration: 15,
      description: "Notification to adjacent property owners",
      riskLevel: "medium",
      order: 5,
    },
    {
      name: "Public Hearing",
      avgDuration: 30,
      description: "Planning Commission or Zoning Board hearing",
      riskLevel: "high",
      order: 6,
    },
    {
      name: "Decision and Appeals Period",
      avgDuration: 15,
      description: "Final decision and potential appeals period",
      riskLevel: "medium",
      order: 7,
    },
  ],
  "zoning-variance": [
    {
      name: "Pre-Application Meeting",
      avgDuration: 7,
      description: "Initial consultation with planning staff",
      riskLevel: "low",
      order: 1,
    },
    {
      name: "Application Submission",
      avgDuration: 1,
      description: "Formal application submission with required materials",
      riskLevel: "low",
      order: 2,
    },
    {
      name: "Staff Review",
      avgDuration: 25,
      description: "Planning department review of application",
      riskLevel: "medium",
      order: 3,
    },
    {
      name: "Public Notice",
      avgDuration: 15,
      description: "Notification to adjacent property owners",
      riskLevel: "medium",
      order: 4,
    },
    {
      name: "Public Hearing",
      avgDuration: 25,
      description: "Zoning Board hearing",
      riskLevel: "high",
      order: 5,
    },
    {
      name: "Decision and Appeals Period",
      avgDuration: 15,
      description: "Final decision and potential appeals period",
      riskLevel: "medium",
      order: 6,
    },
  ],
  "design-review": [
    {
      name: "Pre-Application Meeting",
      avgDuration: 7,
      description: "Initial consultation with planning staff",
      riskLevel: "low",
      order: 1,
    },
    {
      name: "Application Submission",
      avgDuration: 1,
      description: "Formal application submission with required materials",
      riskLevel: "low",
      order: 2,
    },
    {
      name: "Staff Review",
      avgDuration: 20,
      description: "Planning department initial review",
      riskLevel: "medium",
      order: 3,
    },
    {
      name: "Design Review Board",
      avgDuration: 30,
      description: "Review by architectural/design review board",
      riskLevel: "high",
      order: 4,
    },
    {
      name: "Revisions",
      avgDuration: 20,
      description: "Revisions based on design review comments",
      riskLevel: "medium",
      order: 5,
    },
    {
      name: "Final Approval",
      avgDuration: 10,
      description: "Final approval of design",
      riskLevel: "low",
      order: 6,
    },
  ],
  "environmental-review": [
    {
      name: "Initial Study",
      avgDuration: 30,
      description: "Preliminary environmental assessment",
      riskLevel: "medium",
      order: 1,
    },
    {
      name: "Determination",
      avgDuration: 15,
      description: "Determination of required environmental document",
      riskLevel: "medium",
      order: 2,
    },
    {
      name: "Draft Document Preparation",
      avgDuration: 60,
      description: "Preparation of draft EIR, MND, or ND",
      riskLevel: "high",
      order: 3,
    },
    {
      name: "Public Review Period",
      avgDuration: 45,
      description: "Public comment period on draft document",
      riskLevel: "high",
      order: 4,
    },
    {
      name: "Response to Comments",
      avgDuration: 30,
      description: "Preparation of responses to public comments",
      riskLevel: "medium",
      order: 5,
    },
    {
      name: "Final Document",
      avgDuration: 20,
      description: "Preparation and certification of final environmental document",
      riskLevel: "medium",
      order: 6,
    },
  ],
}

// Factors that affect approval timeline
export const timelineFactors = [
  {
    factor: "Project Size",
    impact: "high",
    description: "Larger projects typically require more comprehensive review and face greater scrutiny.",
  },
  {
    factor: "Project Complexity",
    impact: "high",
    description: "Projects with complex designs, multiple variances, or unique features face longer review times.",
  },
  {
    factor: "Environmental Sensitivity",
    impact: "high",
    description: "Projects in environmentally sensitive areas may require additional studies and mitigation measures.",
  },
  {
    factor: "Staff Resources",
    impact: "medium",
    description: "Municipality staffing levels and workload can significantly impact processing times.",
  },
  {
    factor: "Community Opposition",
    impact: "high",
    description: "Projects facing significant community opposition often experience delays during public hearings.",
  },
  {
    factor: "Historic District Location",
    impact: "medium",
    description: "Properties in historic districts typically require additional preservation review.",
  },
  {
    factor: "Coastal Zone",
    impact: "high",
    description: "Projects in coastal zones require additional permits from coastal commissions.",
  },
  {
    factor: "Application Completeness",
    impact: "medium",
    description: "Incomplete applications result in requests for additional information and delays.",
  },
  {
    factor: "Developer Responsiveness",
    impact: "medium",
    description: "How quickly developers respond to comments and requests affects timeline.",
  },
  {
    factor: "Political Climate",
    impact: "medium",
    description: "Local political priorities and election cycles can impact project approvals.",
  },
]
