import type { ZoningInfo } from "./types"

export const zoningData: ZoningInfo[] = [
  {
    city: "Los Angeles",
    county: "Los Angeles",
    zoningType: "R1",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 100,
    maxHeight: 33,
    maxCoverage: 45,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Special hillside regulations may apply in designated areas.",
    coordinates: {
      lat: 34.0522,
      lng: -118.2437,
    },
  },
  {
    city: "San Francisco",
    county: "San Francisco",
    zoningType: "RH-1",
    minLotSize: 2500,
    minLotWidth: 25,
    minLotDepth: 70,
    maxHeight: 40,
    maxCoverage: 55,
    maxStories: 3,
    setbacks: {
      front: 15,
      rear: 25,
      side: 3,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 25,
    notes: "Height limits vary by neighborhood district.",
    coordinates: {
      lat: 37.7749,
      lng: -122.4194,
    },
  },
  {
    city: "San Diego",
    county: "San Diego",
    zoningType: "RS-1-7",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 95,
    maxHeight: 30,
    maxCoverage: 50,
    maxStories: 2,
    setbacks: {
      front: 15,
      rear: 13,
      side: 4,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit", "Home occupation"],
    openSpaceReq: 35,
    notes: "Coastal overlay zone may have additional restrictions.",
    coordinates: {
      lat: 32.7157,
      lng: -117.1611,
    },
  },
  {
    city: "Sacramento",
    county: "Sacramento",
    zoningType: "R1",
    minLotSize: 5200,
    minLotWidth: 52,
    minLotDepth: 100,
    maxHeight: 35,
    maxCoverage: 40,
    maxStories: 2,
    setbacks: {
      front: 25,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit", "Home occupation"],
    openSpaceReq: 30,
    notes: "Recent changes allow for more flexible ADU development.",
    coordinates: {
      lat: 38.5816,
      lng: -121.4944,
    },
  },
  {
    city: "Fresno",
    county: "Fresno",
    zoningType: "RS-5",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 100,
    maxHeight: 35,
    maxCoverage: 40,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 20,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Special permits may be required for home-based businesses.",
    coordinates: {
      lat: 36.7378,
      lng: -119.7871,
    },
  },
  {
    city: "Long Beach",
    county: "Los Angeles",
    zoningType: "R1-N",
    minLotSize: 4000,
    minLotWidth: 40,
    minLotDepth: 100,
    maxHeight: 28,
    maxCoverage: 45,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 10,
      side: 3,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 20,
    notes: "Coastal zone properties have additional development standards.",
    coordinates: {
      lat: 33.7701,
      lng: -118.1937,
    },
  },
  {
    city: "Oakland",
    county: "Alameda",
    zoningType: "RL",
    minLotSize: 5000,
    minLotWidth: 45,
    minLotDepth: 100,
    maxHeight: 30,
    maxCoverage: 40,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 20,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit", "Home occupation"],
    openSpaceReq: 40,
    notes: "Hillside overlay districts have additional requirements for slope stability.",
    coordinates: {
      lat: 37.8044,
      lng: -122.2711,
    },
  },
  {
    city: "Bakersfield",
    county: "Kern",
    zoningType: "R1",
    minLotSize: 6000,
    minLotWidth: 60,
    minLotDepth: 100,
    maxHeight: 35,
    maxCoverage: 40,
    maxStories: 2,
    setbacks: {
      front: 25,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Oil well buffer zones may apply in certain areas.",
    coordinates: {
      lat: 35.3733,
      lng: -119.0187,
    },
  },
  {
    city: "Anaheim",
    county: "Orange",
    zoningType: "RS-1",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 100,
    maxHeight: 30,
    maxCoverage: 45,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 25,
    notes: "Resort district has special development standards.",
    coordinates: {
      lat: 33.8366,
      lng: -117.9143,
    },
  },
  {
    city: "Santa Ana",
    county: "Orange",
    zoningType: "R1",
    minLotSize: 6000,
    minLotWidth: 60,
    minLotDepth: 100,
    maxHeight: 27,
    maxCoverage: 35,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 20,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Historic districts have additional design requirements.",
    coordinates: {
      lat: 33.7455,
      lng: -117.8677,
    },
  },
  {
    city: "Riverside",
    county: "Riverside",
    zoningType: "R1-7000",
    minLotSize: 7000,
    minLotWidth: 65,
    minLotDepth: 100,
    maxHeight: 35,
    maxCoverage: 50,
    maxStories: 2,
    setbacks: {
      front: 25,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit", "Home occupation"],
    openSpaceReq: 35,
    notes: "Arroyo areas have special environmental considerations.",
    coordinates: {
      lat: 33.9806,
      lng: -117.3755,
    },
  },
  {
    city: "Irvine",
    county: "Orange",
    zoningType: "R1",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 90,
    maxHeight: 30,
    maxCoverage: 45,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 40,
    notes: "HOA restrictions may apply in addition to zoning requirements.",
    coordinates: {
      lat: 33.6846,
      lng: -117.8265,
    },
  },
  {
    city: "San Jose",
    county: "Santa Clara",
    zoningType: "R1-8",
    minLotSize: 8000,
    minLotWidth: 70,
    minLotDepth: 100,
    maxHeight: 30,
    maxCoverage: 40,
    maxStories: 2,
    setbacks: {
      front: 25,
      rear: 20,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit", "Home occupation"],
    openSpaceReq: 30,
    notes: "Recent ordinances have expanded ADU development rights.",
    coordinates: {
      lat: 37.3382,
      lng: -121.8863,
    },
  },
  {
    city: "Santa Barbara",
    county: "Santa Barbara",
    zoningType: "R1",
    minLotSize: 7000,
    minLotWidth: 60,
    minLotDepth: 90,
    maxHeight: 30,
    maxCoverage: 40,
    maxStories: 2,
    setbacks: {
      front: 25,
      rear: 15,
      side: 10,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 40,
    notes: "Design review required in many neighborhoods for exterior changes.",
    coordinates: {
      lat: 34.4208,
      lng: -119.6982,
    },
  },
  {
    city: "Santa Monica",
    county: "Los Angeles",
    zoningType: "R1",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 100,
    maxHeight: 28,
    maxCoverage: 35,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 15,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Coastal zone properties have additional development standards.",
    coordinates: {
      lat: 34.0195,
      lng: -118.4912,
    },
  },
  {
    city: "Palo Alto",
    county: "Santa Clara",
    zoningType: "R1",
    minLotSize: 6000,
    minLotWidth: 60,
    minLotDepth: 100,
    maxHeight: 30,
    maxCoverage: 35,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 20,
      side: 6,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 35,
    notes: "Tree preservation ordinances may limit development footprint.",
    coordinates: {
      lat: 37.4419,
      lng: -122.143,
    },
  },
  {
    city: "Berkeley",
    county: "Alameda",
    zoningType: "R1",
    minLotSize: 5000,
    minLotWidth: 50,
    minLotDepth: 80,
    maxHeight: 28,
    maxCoverage: 40,
    maxStories: 3,
    setbacks: {
      front: 20,
      rear: 20,
      side: 4,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit", "Home occupation"],
    openSpaceReq: 40,
    notes: "Hillside overlay district has additional requirements.",
    coordinates: {
      lat: 37.8715,
      lng: -122.273,
    },
  },
  {
    city: "Pasadena",
    county: "Los Angeles",
    zoningType: "RS",
    minLotSize: 7200,
    minLotWidth: 55,
    minLotDepth: 100,
    maxHeight: 32,
    maxCoverage: 35,
    maxStories: 2,
    setbacks: {
      front: 25,
      rear: 25,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Historic districts have additional design requirements.",
    coordinates: {
      lat: 34.1478,
      lng: -118.1445,
    },
  },
  {
    city: "Newport Beach",
    county: "Orange",
    zoningType: "R1",
    minLotSize: 6000,
    minLotWidth: 60,
    minLotDepth: 90,
    maxHeight: 29,
    maxCoverage: 45,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 20,
      side: 4,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 30,
    notes: "Coastal zone and bay front properties have special requirements.",
    coordinates: {
      lat: 33.6189,
      lng: -117.9298,
    },
  },
  {
    city: "Huntington Beach",
    county: "Orange",
    zoningType: "RL",
    minLotSize: 6000,
    minLotWidth: 60,
    minLotDepth: 100,
    maxHeight: 35,
    maxCoverage: 50,
    maxStories: 2,
    setbacks: {
      front: 20,
      rear: 10,
      side: 5,
    },
    allowedUses: ["Single-family dwelling", "Accessory dwelling unit"],
    openSpaceReq: 25,
    notes: "Coastal zone properties have additional development standards.",
    coordinates: {
      lat: 33.6595,
      lng: -117.9988,
    },
  },
]
